version: '2'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - jekyll_bundle:/usr/local/bundle
      - jekyll_gems:/usr/gem

volumes:
  jekyll_bundle:
  jekyll_gems:
